# syntax=docker/dockerfile:1.7
FROM maven:3.9-eclipse-temurin-21
WORKDIR /workspace/app

COPY pom.xml mvnw .
COPY .mvn .mvn
RUN chmod +x mvnw \
    && ./mvnw -B -ntp dependency:go-offline

COPY src src
CMD ["./mvnw", "-B", "verify"]
