name: Deploy Application

on:
  push:
    branches: [ main ]

jobs:
  sonarcloud:
    uses: genzitizens/ci-templates/.github/workflows/sonarcloud.yml@main
    with:
      projectBaseDir: "." # optional if using default
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

  push-ghcr:
    needs: sonarcloud
    uses: genzitizens/ci-templates/.github/workflows/springboot-push-to-ghcr.yml@main
    with:
      image_name: task-management
    secrets:
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
      GHCR_ORG: ${{ secrets.GHCR_ORG }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
